// taskAnalysisData.js
// FONTE ÚNICA DE TASK ANALYSIS – NÍVEIS 1, 2 E 3
import { LEVEL_1_TASK_ANALYSIS } from "./taskAnalysisLevel1";
import { LEVEL_2_TASKS } from "./taskAnalysisLevel2";
import { LEVEL_3_TASKS } from "./taskAnalysisLevel3";

export const TASK_ANALYSIS_MAP_BY_LEVEL = {
    1: {
        "BRINCAR INDEPENDENTE": LEVEL_1_TASK_ANALYSIS.BRINCAR,
        "COMPORTAMENTO SOCIAL E BRINCAR SOCIAL": LEVEL_1_TASK_ANALYSIS.SOCIAL,
        "HABILIDADES PERCEPTUAIS VISUAIS E PAREAMENTO AO MODELO": LEVEL_1_TASK_ANALYSIS.VP_MTS,
        "IMITAÇÃO": LEVEL_1_TASK_ANALYSIS.IMITACAO,
        "MANDO": LEVEL_1_TASK_ANALYSIS.MANDO,
        "OUVINTE": LEVEL_1_TASK_ANALYSIS.OUVINTE,
        "TATO": LEVEL_1_TASK_ANALYSIS.TATO,
        "COMPORTAMENTO VOCAL ESPONTÂNEO": [],
        "GENERALIZAÇÃO": []
    },
    2: {
        "MANDO": LEVEL_2_TASKS.MANDO,
        "TATO": LEVEL_2_TASKS.TATO,
        "OUVINTE": LEVEL_2_TASKS.OUVINTE,
        "HABILIDADES PERCEPTUAIS VISUAIS E PAREAMENTO AO MODELO": LEVEL_2_TASKS.PERCEPCAO_VISUAL,
        "BRINCAR INDEPENDENTE": LEVEL_2_TASKS.BRINCAR,
        "COMPORTAMENTO SOCIAL E BRINCAR SOCIAL": LEVEL_2_TASKS.SOCIAL,
        "IMITAÇÃO": LEVEL_2_TASKS.IMITACAO,
        "RESPOSTA DE OUVINTE POR FUNÇÃO, CARACTERÍSTICA E CLASSE": LEVEL_2_TASKS.FCC,
        "INTRAVERBAL": LEVEL_2_TASKS.INTRAVERBAL,
        "ROTINAS DE CLASSE E HABILIDADES DE GRUPO": LEVEL_2_TASKS.ROTINA_GRUPO,
        "ESTRUTURA LINGUÍSTICA": LEVEL_2_TASKS.ESTRUTURA_LINGUISTICA,
        "LINGUÍSTICA": LEVEL_2_TASKS.ESTRUTURA_LINGUISTICA // Fallback para variação de nome
    },
    3: {
        "MANDO": LEVEL_3_TASKS.MANDO,
        "TATO": LEVEL_3_TASKS.TATO,
        "OUVINTE": LEVEL_3_TASKS.OUVINTE,
        "HABILIDADES PERCEPTUAIS VISUAIS E PAREAMENTO AO MODELO": LEVEL_3_TASKS.VP_MTS,
        "BRINCAR INDEPENDENTE": LEVEL_3_TASKS.BRINCAR,
        "COMPORTAMENTO SOCIAL E BRINCAR SOCIAL": LEVEL_3_TASKS.SOCIAL,
        "RESPOSTA DE OUVINTE POR FUNÇÃO, CARACTERÍSTICA E CLASSE": LEVEL_3_TASKS.ROFCC,
        "INTRAVERBAL": LEVEL_3_TASKS.INTRAVERBAL,
        "ROTINAS DE CLASSE E HABILIDADES DE GRUPO": LEVEL_3_TASKS.ROTINA_GRUPO,
        "ESTRUTURA LINGUÍSTICA": LEVEL_3_TASKS.ESTRUTURA_LINGUISTICA,
        "LEITURA": LEVEL_3_TASKS.LEITURA,
        "ESCRITA": LEVEL_3_TASKS.ESCRITA,
        "MATEMÁTICA": LEVEL_3_TASKS.MATEMATICA
    }
};

// Mantendo compatibilidade legada se necessário
export const TASK_ANALYSIS_MAP = TASK_ANALYSIS_MAP_BY_LEVEL[1];
