// taskAnalysisLevel1.js
// VB-MAPP – Task Analysis – NÍVEL 1 (INTEGRAL E REVISADO)

export const LEVEL_1_TASK_ANALYSIS = {
    MANDO: [
        { id: "1-a", texto: "Faz contato visual (troca o olhar) como um mando por atenção ou outros reforçadores por 2 vezes (O)" },
        { id: "1-b", texto: "Aproxima-se de um item reforçador para indicar a presença de uma OM por 2 vezes (O)" },
        { id: "1-c", texto: "Puxa um adulto para acessar um item reforçador por 2 vezes (O)" },
        { id: "1-d", texto: "Aponta ou gesticula em direção a um reforçador para acessá-lo por 2 vezes (O)" },
        { id: "2-a", texto: "Aponta para dois reforçadores diferentes a fim acessá-los por 2 vezes (T/O)" },
        { id: "2-b", texto: "Acena ou diz sim ou não quando lhe é oferecido um reforçador por 2 vezes (T/O)" },
        { id: "2-c", texto: "Emite 2 mandos diferentes sem dica ecoica – pode ser com dica verbal ou com objeto (T/O)" },
        { id: "2-d", texto: "Espontaneamente emite 1 mando sem dica imitativa ou ecoica - pode ser com objeto (O)" },
        { id: "2-e", texto: "Generaliza 2 mandos conhecidos entre 2 pessoas diferentes e 2 ambientes (T/O)" },
        { id: "3-a", texto: "Emite 2 mandos espontâneos (sem dica verbal) - o objeto pode estar presente (O)" },
        { id: "3-b", texto: "Emite 10 mandos sem dica ecoica ou imitativa - pode ser com dica verbal ou com objeto (O)" },
        { id: "3-c", texto: "Generaliza 3 mandos entre 2 exemplares de um item desejado (ex. pede escorregador para 2 diferentes) (T/O)" },
        { id: "3-d", texto: "Emite 6 mandos diferentes sem dica ecoica ou imitativa (T/O)" },
        { id: "4-a", texto: "Solicita atenção 2 vezes com algum tipo de resposta identificável (ex. tocar no braço) (O)" },
        { id: "4-b", texto: "Emite 2 mandos sem o objeto presente – pode ser com 'O que você quer?' (O)" },
        { id: "4-c", texto: "Emite 2 mandos sem dicas verbais – pode ser com objeto (O)" },
        { id: "4-d", texto: "Pede para os outros atentarem para os mesmos estímulos que está olhando por 5 vezes ao dia (O)" },
        { id: "4-e", texto: "Emite 1 mando para remover um item ou atividade indesejados (ex. não) (T/O)" },
        { id: "5-a", texto: "Emite 3 diferentes mandos sem objeto presente – pode ser com uma dica verbal (ex. mamãe) (T/O)" },
        { id: "5-b", texto: "Emite 3 diferentes mandos sem dicas verbais – pode ser com dica com objeto (T/O)" },
        { id: "5-c", texto: "Os mandos contêm entonações que variam e são apropriados à OM atual 2 vezes (O)" },
        { id: "5-d", texto: "Adquire um novo mando em menos de 20 tentativas de treino (T)" },
        { id: "5-e", texto: "Continua a emitir um mando 2 vezes se o reforçador não é entregue - persistência (T/O)" }
    ],

    TATO: [
        { id: "1-a", texto: "Tateia pessoa familiar, animal ou objeto com dicas verbais e motivação (ex. mamãe) (T/O)" },
        { id: "3-a", texto: "Generaliza respostas conhecidas entre 2 pessoas e 2 ambientes (T/O)" },
        { id: "3-b", texto: "Generaliza tatos entre 2 exemplares de um item para 2 itens (ex. 2 telefones diferentes) (T)" },
        { id: "4-a", texto: "Olha para fotos familiares e, com dicas verbais, tateia 2 membros familiares (T)" },
        { id: "4-b", texto: "Tateia 2 figuras (2D) em livro ou cartão (ex. pato, bola) (T)" },
        { id: "5-a", texto: "Tateia 5 figuras (2D) (T)" },
        { id: "5-b", texto: "Mantém tato recém adquirido após 24h sem treino (T)" },
        { id: "5-c", texto: "Generaliza tatos entre 3 exemplares para 5 itens (ex. 3 colheres diferentes) (T)" }
    ],

    OUVINTE: [
        { id: "1-a", texto: "Vira a cabeça para localizar origem de som (ex. campainha, telefone) (O)" },
        { id: "2-a", texto: "Sorri ao som da voz do cuidador 2 vezes (O)" },
        { id: "3-a", texto: "Interrompe a brincadeira quando o nome é chamado (T/O)" },
        { id: "3-b", texto: "Responde ao não, quente, pare ou outros comandos em contexto apropriado (O)" },
        { id: "3-c", texto: "Atenta para objeto ou figura quando nomeados (sem discriminação) 5 vezes (O)" },
        { id: "3-d", texto: "Responde a 2 instruções verbais simples em um contexto (ex. 'sente') (T/O)" },
        { id: "3-e", texto: "Discrimina 2 membros familiares ou animais quando nomeados (T/O)" },
        { id: "3-f", texto: "Discrimina 2 objetos apresentados no nível dos olhos (ex. bola vs sapato) (T)" },
        { id: "4-a", texto: "Seleciona item correto em conjunto de 2 para 10 itens diferentes (T)" },
        { id: "4-b", texto: "Mantém contato visual com o falante por 2 segundos (O)" },
        { id: "4-c", texto: "Toca 2 partes do corpo sob comando (ex. nariz, orelhas) (T)" },
        { id: "4-d", texto: "Executa 2 ações motoras sob comando (ex. bater palmas, girar) (T)" },
        { id: "4-e", texto: "Seleciona item correto em conjunto de 3 para 10 itens diferentes (T)" },
        { id: "4-f", texto: "Generaliza discriminação de ouvinte entre 2 exemplares de 5 itens (T)" },
        { id: "5-a", texto: "Identifica 5 itens em teste de fluência (período de 10 segundos) (T)" },
        { id: "5-b", texto: "Demonstra 6 ações motoras sob comando sem dica visual (T)" },
        { id: "5-c", texto: "Mantém habilidade de ouvinte adquirida após 24h sem treino (T)" },
        { id: "5-d", texto: "Emite espontaneamente uma resposta de ouvinte 2 vezes (O)" },
        { id: "5-e", texto: "Generaliza tarefas de ouvinte entre 3 pessoas, 3 ambientes e 3 vezes no dia (T)" }
    ],

    VP_MTS: [
        { id: "1-a", texto: "Atenta visualmente para faces e pessoas 5 vezes (O)" },
        { id: "1-b", texto: "Atenta visualmente para objetos reforçadores 5 vezes (O)" },
        { id: "2-a", texto: "Alcança e agarra objetos com sucesso 5 vezes (T/O)" },
        { id: "2-b", texto: "Usa dedo indicador para cutucar ou outros usos 5 vezes (O)" },
        { id: "2-c", texto: "Manipula objetos de forma variada por 10 segundos, 5 vezes (O)" },
        { id: "3-a", texto: "Transfere objetos entre mãos 5 vezes (O)" },
        { id: "3-b", texto: "Procura objeto que caiu fora da vista 5 vezes (O)" },
        { id: "4-a", texto: "Despeja objetos de recipientes ou puxa de armários 5 vezes (O)" },
        { id: "4-b", texto: "Empurra ou puxa objetos 5 vezes (O)" },
        { id: "5-a", texto: "Atenta visualmente para brinquedos/livros por 1 minuto, 2 vezes (O)" },
        { id: "5-b", texto: "Usa colher com sucesso 5 vezes durante uma refeição (O)" },
        { id: "5-c", texto: "Completa quebra-cabeça de 3 peças sem dica física (T/O)" },
        { id: "5-d", texto: "Rabisca com qualquer objeto de escrita (O)" },
        { id: "5-e", texto: "Coloca 2 itens similares juntos 2 vezes (O)" }
    ],

    BRINCAR: [
        { id: "1-a", texto: "Possui item de conforto favorito (ex. cobertor, pelúcia) (O)" },
        { id: "1-b", texto: "Direciona-se a objetos de interesse (ex. chaves, bola) (O)" },
        { id: "1-c", texto: "Transfere itens entre mãos (O)" },
        { id: "1-d", texto: "Olha para brinquedo quando pego por adulto (O)" },
        { id: "2-a", texto: "Aponta para brinquedo ou objeto de interesse (O)" },
        { id: "2-b", texto: "Explora causa e efeito (ex. derrubar itens para ver cair) (O)" },
        { id: "2-c", texto: "Abre armários, caixas ou alcança recipientes de brinquedos (O)" },
        { id: "2-d", texto: "Repete brincadeira que produz som (ex. aperta brinquedo sonoro) (O)" },
        { id: "2-e", texto: "Faz contato visual com outros 3 vezes durante a brincadeira (O)" },
        { id: "3-a", texto: "Leva brinquedo ou objeto de interesse ao adulto (O)" },
        { id: "3-b", texto: "Despeja itens de um recipiente no chão (O)" },
        { id: "3-c", texto: "Transfere itens para dentro ou fora do container (O)" },
        { id: "3-d", texto: "Generaliza brincar em novos ambientes (O)" },
        { id: "3-e", texto: "Carrega objetos ou brinquedos de um lugar para o outro (O)" },
        { id: "4-a", texto: "Entra em casa de brinquedo sem dica verbal do adulto (O)" },
        { id: "4-b", texto: "Manipula brinquedo corretamente após demonstração (O)" },
        { id: "4-c", texto: "Emite mando para ajuda com item (ex. mostra algo que não abre) (O)" },
        { id: "4-d", texto: "Dança espontaneamente quando música é tocada (O)" },
        { id: "4-e", texto: "Gosta de ser conduzido em veículos de brinquedo (triciclo, vagão) (O)" },
        { id: "4-M", texto: "Engaja-se em brincadeira de movimento por 2 minutos (balanço, dança) (O)" },
        { id: "5-a", texto: "Leva peças de um conjunto separado (ex. Duplos, Bristleblocks) (O)" },
        { id: "5-b", texto: "Empurra e puxa itens em torno de si espontaneamente (O)" },
        { id: "5-c", texto: "Carrega objeto grande para novo local (ex. garagem de brinquedo) (O)" },
        { id: "5-d", texto: "Emite sons ou palavras associados a brinquedos (ex. 'Vroom') (O)" },
        { id: "5-e", texto: "Conecta coisas ou coloca-las juntas (ex. carro na pista) (O)" }
    ],

    SOCIAL: [
        { id: "1-a", texto: "Sorri ao ouvir vozes familiares 3 vezes (TO: 60 min)" },
        { id: "1-b", texto: "Olha para faces conhecidas ao menos 3 vezes (TO: 60 min)" },
        { id: "1-c", texto: "Orienta-se ou faz contato visual com conhecidos 5 vezes (TO: 30 min)" },
        { id: "2-a", texto: "Sorri ou gargalha em brincadeiras físicas 5 vezes (T/O)" },
        { id: "2-b", texto: "Participa de brincadeira social recíproca 2 vezes (ex. esconde-esconde) (T)" },
        { id: "2-c", texto: "Procura atenção do adulto (olhar, sons, gestos) 3 vezes (TO: 60 min)" },
        { id: "3-a", texto: "Pega item desejado de adulto 3 vezes (T)" },
        { id: "3-b", texto: "Reage positivamente à aproximação de outras crianças 2 vezes (O)" },
        { id: "3-c", texto: "Responde a cumprimentos com 2 segundos de contato visual 2 vezes (T/O)" },
        { id: "4-a", texto: "Aproxima-se de outra criança 2 vezes com dica do adulto (TO: 30 min)" },
        { id: "4-b", texto: "Fica perto de outra criança em atividade de grupo 2 vezes (TO: 30 min)" },
        { id: "4-c", texto: "Imita aceno de tchau para outros com dica 2 vezes (T/O)" },
        { id: "4-d", texto: "Senta próximo de outra criança em grupo 2 vezes com dica (O)" },
        { id: "5-a", texto: "Segue outras crianças espontaneamente 2 vezes (O)" },
        { id: "5-b", texto: "Imita comportamento de outras crianças espontaneamente 2 vezes (O)" },
        { id: "5-c", texto: "Ri espontaneamente quando outros fazem comportamentos bobos 2 vezes (O)" }
    ],

    IMITACAO: [
        { id: "1-a", texto: "Imita movimentos com a boca 3 vezes (ex. abrir boca) (O)" },
        { id: "1-b", texto: "Imita 1 movimento de outra pessoa sob solicitação (T)" },
        { id: "2-a", texto: "Imita 2 ações com objetos (ex. bater martelo, rolar bola) (T)" },
        { id: "2-b", texto: "Imita atividades divertidas espontaneamente 2 vezes (O)" },
        { id: "2-c", texto: "Faz contato visual enquanto imita 3 vezes (TO: 30 min)" },
        { id: "3-a", texto: "Imita 2 movimentos motores finos (ex. estalar dedos, abrir punho) (T)" },
        { id: "3-b", texto: "Imita movimentos motores grossos espontaneamente 2 vezes (O)" },
        { id: "3-c", texto: "Imita balançar do corpo quando está lado a lado (T)" },
        { id: "3-d", texto: "Generaliza imitação conhecida para 2 novas pessoas (T)" },
        { id: "4-a", texto: "Imita apontando para pessoas ou objetos (T)" },
        { id: "4-b", texto: "Imita transferindo objetos entre mãos (T)" },
        { id: "4-c", texto: "Imita 5 ações que produzem efeito (ex. apertar botões sonoros) (T)" },
        { id: "4-d", texto: "Imita 2 movimentos com a cabeça (ex. sim/não) (T)" },
        { id: "5-a", texto: "Imita 5 movimentos motores finos (ex. pinça, cutucar) (T)" },
        { id: "5-b", texto: "Imita comportamento motor grosso de outras crianças 2 vezes com dica (T)" },
        { id: "5-c", texto: "Imita comportamento de outros espontaneamente 2 vezes (T)" },
        { id: "5-d", texto: "Generaliza 10 respostas de imitação para 3 pessoas novas (T)" }
    ]
};