// taskAnalysisLevel3.js
// VB-MAPP – Task Analysis – NÍVEL 3 (INTEGRAL - TODOS OS SUBITENS)

export const LEVEL_3_TASKS = {
    MANDO: [
        { id: "11-a", texto: "Mandos para os colegas 5 vezes (O)" },
        { id: "11-b", texto: "Espontaneamente pede por atenção por 5 vezes (ex. Professor! Ei! Com licença) (O)" },
        { id: "11-c", texto: "A criança emite 100 ou mais mandos diferentes em um período de uma semana (TO: 1 semana)" },
        { id: "11-d", texto: "Mandos possuem frases com 3-palavras por 10 vezes (ex. Eu posso ver?) (O)" },
        { id: "11-e", texto: "Mandos para uma quantidade específica de reforçadores 2 vezes (ex. 2 balas de urso) (O)" },
        { id: "12-a", texto: "Mandos para remover um item aversivo ou uma atividade 2 vezes (ex. Deixe-me ir) (T/O)" },
        { id: "12-b", texto: "Mandos para outras pessoas executarem ações que envolvem 2-sequencias 2 vezes (O)" },
        { id: "12-c", texto: "Diz por favor e obrigado com dica indireta de adultos (ex. O que você diz?) (T/O)" },
        { id: "12-d", texto: "Demonstra OM generalizada pedindo de 2 reforçadores diferentes com as mesmas palavras (O)" },
        { id: "12-e", texto: "Mandos para outro participarem em uma atividade 2 vezes (ex. Vem jogar) (O)" },
        { id: "13-a", texto: "Espontaneamente pede para usar o banheiro 2 vezes (O)" },
        { id: "13-b", texto: "Pede para outros atendam ao seu próprio comportamento não verbal 2 vezes (O)" },
        { id: "13-c", texto: "Pede para outros atendam a algum aspecto do ambiente 2 vezes (ex. Olhe, é um caminhão) (O)" },
        { id: "13-d", texto: "Mandos com dois diferentes adjetivos (ex. Eu quero uma bala de urso vermelha) (O)" },
        { id: "13-e", texto: "Mandos com duas preposições diferentes (ex. Coloque isso na casa) (O)" },
        { id: "13-f", texto: "Mandos com dois advérbios diferentes (O)" },
        { id: "14-a", texto: "Pede por simpatia ou suporte emocional 2 vezes (ex. Ele é ruim) (O)" },
        { id: "14-b", texto: "Pede para outros entreguem um objeto específico para uma outra pessoa (T/O)" },
        { id: "14-c", texto: "Manda por instrução para completar uma tarefa 2 vezes (ex. Onde isso vai?) (O)" },
        { id: "14-d", texto: "Espontaneamente manda utilizando 3 componentes principais (subst-verbo-adj) (O)" },
        { id: "15-a", texto: "Mandos com frases ou sentenças contendo 5 palavras 10 vezes (TO: 60min)" },
        { id: "15-b", texto: "Mandos para informação sobre eventos futuros 2 vezes (ex. Quando vamos para a festa?) (O)" },
        { id: "15-c", texto: "Mandos para ter atenção com relação a um evento privado 2 vezes (ex. Meu estômago dói) (O)" },
        { id: "15-d", texto: "Mandos para informação 5 vezes usando 'Por que' nas perguntas (O)" },
        { id: "15-e", texto: "Mandos para informação usando 'Como' nas perguntas (O)" }
    ],

    TATO: [
        { id: "11-a", texto: "Tateia 2 estímulos olfativos (ex. biscoitos, pipoca e flores) (T/O)" },
        { id: "11-b", texto: "Adquire 5 novos tatos em uma semana sem treino direto (T/O)" },
        { id: "11-c", texto: "Tateia 2 pessoas (sem ser da família) pelos seus primeiros nomes (T/O)" },
        { id: "11-d", texto: "Tateia 5 categorias ou classes (ex. animais, bebidas ou brinquedos) (T)" },
        { id: "11-e", texto: "Tateia 5 locais (ex. cozinha, quarto, área de lazer) (T)" },
        { id: "11-f", texto: "Tateia 25 itens e/ou atividades com sim e não (T)" },
        { id: "11-g", texto: "Tateia a função de 25 itens (ex. O que você faz com isso?) (T)" },
        { id: "11-h", texto: "Tateia 2 características específicas ou parte de 25 itens ou pessoas (T/O)" },
        { id: "11-i", texto: "Generalização para novos exemplos de um item ou ação na 1ª tentativa para 5 itens (T/O)" },
        { id: "12-a", texto: "Tateia a classe de 25 itens (ex. O cachorro é um...) (T)" },
        { id: "12-b", texto: "Tateia o que é errado ou está faltando em 10 figuras ou objetos (T)" },
        { id: "12-c", texto: "Tateia a classe e a função de 10 itens (T)" },
        { id: "12-d", texto: "Tateia 2 relações preposicionais (ex. Onde está Oscar? na lata) (T)" },
        { id: "12-e", texto: "Tateia pessoas com 2 pronomes diferentes (ex. Você tem) (T)" },
        { id: "12-f", texto: "Espontaneamente tateia a função, característica ou classe para 5 itens (O)" },
        { id: "12-g", texto: "Generaliza tatos de característica, função ou classe para 10 novos membros (T)" },
        { id: "13-a", texto: "Tateia pessoas por gênero usando 4 termos (menina, menino, homem, mulher) (T)" },
        { id: "13-b", texto: "Tateia espontaneamente o comportamento de outros 2 vezes (O)" },
        { id: "13-c", texto: "Tateia 2 pares de adjetivos relativos (ex. grande/pequeno; longo/curto) (T)" },
        { id: "13-d", texto: "Tateia espontaneamente com 2 adjetivos diferentes (O)" },
        { id: "13-e", texto: "Tateia espontaneamente com 2 advérbios diferentes (O)" },
        { id: "13-f", texto: "Tateia espontaneamente a posse de itens 2 vezes (ex. meu, seu) (O)" },
        { id: "14-a", texto: "Tateia pessoas por relação usando 4 termos (ex. irmã, avó, tio) (T/O)" },
        { id: "14-b", texto: "Tateia 5 combinações adjetivo-substantivo em sentença completa (T/O)" },
        { id: "14-c", texto: "Tateia 5 combinações verbo-advérbio em sentença completa (T/O)" },
        { id: "14-d", texto: "Tateia 5 combinações preposição-substantivo em sentença completa (T/O)" },
        { id: "14-e", texto: "Tateia 5 combinações sujeito-verbo-substantivo em sentença completa (T)" },
        { id: "15-a", texto: "Tateia 3 estados emocionais próprios ou de outros (T/O)" },
        { id: "15-b", texto: "Tateia 5 gestos usados frequentemente que tem uma função verbal (T)" },
        { id: "15-c", texto: "Tateia 5 ajudantes da comunidade (policial, bombeiro, médico) (T)" },
        { id: "15-d", texto: "Tateia 2 palavras de negação diferentes 5 vezes (ex. Isto não é um gato) (T)" },
        { id: "15-e", texto: "Tateia 5 eventos sociais, comunitários ou de grupo (festa, desfile) (T)" },
        { id: "15-f", texto: "Tateia espontaneamente 2 circunstâncias sociais (O)" },
        { id: "15-g", texto: "Emite espontaneamente tatos não-treinados em sentenças de 5 palavras (O)" }
    ],

    OUVINTE: [
        { id: "11-a", texto: "Coloca 5 itens especificados em seu lugar (ex. Retirar a escova) (T)" },
        { id: "11-b", texto: "Discrimina entre 4 cores num arranjo de 4 objetos (T)" },
        { id: "11-c", texto: "Discrimina entre 4 formas num arranjo de 4 formas (T)" },
        { id: "11-d", texto: "Discrimina entre 2 preposições diferentes (ex. dentro, sobre, embaixo) (T)" },
        { id: "11-e", texto: "Discrimina entre si mesmo e outros através de um pronome (T)" },
        { id: "11-f", texto: "Seleciona duas cores ou formas diferentes de um arranjo de 8 ou 10 (T)" },
        { id: "12-a", texto: "Segue instruções para pegar um item em 5 localizações diferentes (T)" },
        { id: "12-b", texto: "Vai a 5 localizações diferentes e retorna objetos específicos (T)" },
        { id: "12-c", texto: "Seleciona itens baseados em um adjetivo (ex. Toque o pássaro pequeno) (T)" },
        { id: "12-d", texto: "Discrimina entre gêneros (menina/menino e homem/mulher) (T)" },
        { id: "12-e", texto: "Discrimina entre masculino e feminino dado um pronome (ele/ela) (T)" },
        { id: "12-f", texto: "Demonstra ações modificadas por 2 advérbios (ex. rápido/devagar) (T)" },
        { id: "13-a", texto: "Demonstra 3 emoções quando solicitado (ex. cara triste/feliz) (T)" },
        { id: "13-b", texto: "Identifica 10 itens baseado em sujeito, adjetivo e substantivo (T)" },
        { id: "13-c", texto: "Executa 10 ações baseado em um sujeito, preposição e substantivo (T)" },
        { id: "13-d", texto: "Identifica 10 itens baseado em um verbo, pronome e substantivo (T)" },
        { id: "13-e", texto: "Generaliza um pronome e uma preposição a uma nova situação (T)" },
        { id: "14-a", texto: "Executa 10 ações baseado em um sujeito, verbo e advérbio (T)" },
        { id: "14-b", texto: "Executa 10 ações baseado em um sujeito, adjetivo e verbo (T)" },
        { id: "14-c", texto: "Discrimina entre 6 ajudantes comunitários por categoria (T)" },
        { id: "14-d", texto: "Responde corretamente a 10 tarefas envolvendo 'um' vs 'dois' vs 'todos' (T)" },
        { id: "15-a", texto: "Discrimina entre itens a partir de palavras de negação (ex. Qual não é comida?) (T)" },
        { id: "15-b", texto: "Discrimina 5 atributos de pares num grupo pequeno (T)" },
        { id: "15-c", texto: "Responde corretamente a 10 tarefas de singular vs. plural (T)" },
        { id: "15-d", texto: "Generaliza 5 adjetivos para novos nomes (T)" },
        { id: "15-e", texto: "Generaliza 5 advérbios para novos verbos (T)" }
    ],

    VP_MTS: [
        { id: "11-a", texto: "Completa 5 quebra-cabeças interligados com 10 peças (T)" },
        { id: "11-b", texto: "Completa brinquedo de 4 blocos com modelo 2D e blocos 3D para 4 brinquedos (T)" },
        { id: "11-c", texto: "Usa cola para juntar coisas sem ajuda física 2 vezes (T)" },
        { id: "11-d", texto: "Pareia figura de localização para figura não-idêntica de mesma localização (T)" },
        { id: "12-a", texto: "Ordena 5 itens relacionados de 3 categorias diferentes com um modelo (T)" },
        { id: "12-b", texto: "Pareia itens não-idênticos com atraso de 5 segundos (T)" },
        { id: "12-c", texto: "Completa brinquedo de 6 blocos com modelo 2D para 8 blocos (T)" },
        { id: "12-d", texto: "Pareia um brinquedo de blocos 3D com 4 blocos (ex. torre) (T)" },
        { id: "13-a", texto: "Usa tesoura para cortar 5 diferentes padrões sem ajuda física (T)" },
        { id: "13-b", texto: "Organiza uma mesa para duas pessoas com 6 louças e utensílios (T)" },
        { id: "13-c", texto: "Coloca 3 conjuntos de itens em ordem por tamanho (seriação) (T)" },
        { id: "13-d", texto: "Imita estrutura-modelo de blocos com pelo menos 6 partes (T)" },
        { id: "14-a", texto: "Completa com sucesso quebra-cabeça de figura humana com 6 partes (T)" },
        { id: "14-b", texto: "Pareia 25 itens associados em arranjo com 3 estímulos similares (T)" },
        { id: "14-c", texto: "Completa 10 tarefas diferentes de seriação (ex. parte para o todo) (T)" },
        { id: "14-d", texto: "Brinca de um jogo curto de concentração ou memória (T)" },
        { id: "15-a", texto: "Completa um padrão A-B para 5 cores ou formas (T)" },
        { id: "15-b", texto: "Completa um padrão A-B para 5 diferentes padrões de figuras (T)" },
        { id: "15-c", texto: "Coloca 3 figuras na sequência correta para 5 conjuntos (T)" },
        { id: "15-d", texto: "Constrói 5 cenas com sentido (ex. fazenda) com 5 partes (T)" }
    ],

    BRINCAR: [
        { id: "11-a", texto: "Orienta-se em brinquedo de montar/andar em torno de obstruções" },
        { id: "11-b", texto: "Demonstra correspondência 1 para 1 em atividades de brincar (O)" },
        { id: "11-c", texto: "Pega brinquedos e brinca independentemente por 2 minutos (O)" },
        { id: "11-d", texto: "Canta, cantarola ou recita sons familiares durante atividade (O)" },
        { id: "12-a", texto: "Traz uma atividade de montagem para completar (O)" },
        { id: "12-b", texto: "Colore um figura em um livro de colorir ou em um papel (O)" },
        { id: "12-c", texto: "Independentemente senta e olha um livro por 5 minutos (O)" },
        { id: "12-d", texto: "Aceita direcionamento de um par quando está brincando (O)" },
        { id: "13-a", texto: "Usa materiais de arte e ofício como pretendido (tesoura, cola) (O)" },
        { id: "13-b", texto: "Espera por um turno em uma atividade (O)" },
        { id: "13-c", texto: "Independentemente desenha itens reconhecíveis (O)" },
        { id: "13-d", texto: "Apresenta um projeto completo para um adulto ou par (O)" },
        { id: "13-e", texto: "Colore itens dentro de seus limites na maioria das vezes (O)" },
        { id: "14-a", texto: "Resposta apropriada quando atividade é interrompida (O)" },
        { id: "14-b", texto: "Segue regras de segurança (ex. não jogar objetos) (O)" },
        { id: "14-c", texto: "Fingirá escrever um bilhete (O)" },
        { id: "14-d", texto: "Independentemente inicia e guarda uma atividade lúdica (O)" },
        { id: "15-a", texto: "Vontade de experimentar atividades físicas desafiadoras (O)" },
        { id: "15-b", texto: "Espontaneamente ajuda em atividades diárias (pôr a mesa) (O)" },
        { id: "15-c", texto: "Engaja-se em atividade não-preferida para ganhar a preferida (O)" },
        { id: "15-d", texto: "Opera equipamentos de vídeo game ou computador com propriedade (O)" },
        { id: "15-e", texto: "Independentemente resolve problemas encontrados em um jogo (O)" }
    ],

    SOCIAL: [
        { id: "11-a", texto: "Participa de atividades de cooperação com dica de um adulto 2 vezes (O)" },
        { id: "11-b", texto: "Apropriadamente pede aos pares cessar comportamento indesejável (O)" },
        { id: "11-c", texto: "Espera por sua vez para ter um reforçador sem comportamento negativo (O)" },
        { id: "11-d", texto: "Aceita convite para participar de atividade social com pares (O)" },
        { id: "11-e", texto: "Mandos para colegas com pronomes interrogativos 2 vezes (O)" },
        { id: "12-a", texto: "Espontaneamente imita o comportamento de colega em atividade (O)" },
        { id: "12-b", texto: "Espontaneamente manda usando 'Onde' para colega ausente (O)" },
        { id: "12-c", texto: "Espontaneamente manda usando 'O que/Qual' para comportamento de colega (O)" },
        { id: "12-d", texto: "Espontaneamente manda usando 'Quem' evocado por estranho (O)" },
        { id: "12-e", texto: "Tem um 'melhor amigo' (brinca repetidamente com criança específica) (O)" },
        { id: "12-f", texto: "Engaja-se em pelo menos três trocas verbais com um colega (O)" },
        { id: "13-a", texto: "Espontaneamente usa por favor e obrigado com adulto ou colega (O)" },
        { id: "13-b", texto: "Demonstra trocas verbais recíprocas com um colega 2 vezes (O)" },
        { id: "13-c", texto: "Segue instruções dadas por um colega em brincadeira social (O)" },
        { id: "13-d", texto: "Fornece instruções a um colega em atividade social (O)" },
        { id: "13-e", texto: "Espontaneamente oferece um reforçador (compartilha) para colega (O)" },
        { id: "14-a", texto: "Participa de jogo social conduzido por colega (ex. luz verde) (O)" },
        { id: "14-b", texto: "Espontaneamente manda pelo nome de criança nova (O)" },
        { id: "14-c", texto: "Reveza e compartilha reforçadores sem dicas 2 vezes (O)" },
        { id: "14-d", texto: "Gargalha ou sorri de piadas ou humor de colegas (O)" },
        { id: "14-e", texto: "Pergunta sobre interesses dos colegas 1 vez (O)" },
        { id: "15-a", texto: "Engaja-se no mínimo em 3 trocas verbais com um colega (O)" },
        { id: "15-b", texto: "Troca verbal com dois ou mais colegas em um ambiente (O)" },
        { id: "15-c", texto: "Comportamento de enfrentamento adequado quando colega toma reforçador (O)" },
        { id: "15-d", texto: "Atenta a um colega contando uma história por 10 segundos (O)" },
        { id: "15-e", texto: "Narra a atividade de um colega com no mínimo 2 tatos (O)" },
        { id: "15-f", texto: "Espontaneamente demonstra compaixão a colega machucado (O)" },
        { id: "15-g", texto: "Negocia tempo com um reforçador com um colega (O)" }
    ],

    ROFCC: [
        { id: "11-a", texto: "Seleciona 2 membros de uma classe de matriz de 10 para 25 classes (T)" },
        { id: "11-b", texto: "Seleciona 50 itens de um livro dado qualquer tarefa LRFFC (T)" },
        { id: "11-c", texto: "Seleciona 50 itens do ambiente em atividade funcional (T)" },
        { id: "11-d", texto: "Demonstra 200 diferentes respostas de ouvinte por FCC (T)" },
        { id: "11-e", texto: "Seleciona imagem para o próximo passo de uma sequência" },
        { id: "11-f", texto: "Seleciona figura de matriz de 10 dado questão de tempo geral (T)" },
        { id: "12-a", texto: "Seleciona item de matriz de 10 dado cor e classe (T)" },
        { id: "12-b", texto: "Seleciona item de matriz de 10 dado forma e classe (T)" },
        { id: "12-c", texto: "Seleciona item dado função e classe (T)" },
        { id: "12-d", texto: "Seleciona item dado característica e classe (T)" },
        { id: "12-e", texto: "Seleciona item dado adjetivo (não cor/forma) e função (T)" },
        { id: "12-f", texto: "Seleciona item dado adjetivo e característica (T)" },
        { id: "13-a", texto: "Seleciona item de livro após leitura de passagem curta (T)" },
        { id: "13-b", texto: "Seleciona item de matriz de 10 dado preposição e tarefa FCC (T)" },
        { id: "13-c", texto: "Seleciona item de conjunto de 10 dado pronome e tarefa FCC (T)" },
        { id: "13-d", texto: "Seleciona item de conjunto de 10 dado advérbio e tarefa FCC (T)" },
        { id: "13-e", texto: "Seleciona 10 serviços de ajuda à comunidade em livro (T)" },
        { id: "13-f", texto: "Seleciona 2 itens diferentes dados 2 classes ou funções (T)" },
        { id: "13-g", texto: "Seleciona local dado dois itens dessa localidade (T)" },
        { id: "13-h", texto: "Seleciona item em ambiente natural com 3 estímulos similares (T)" },
        { id: "14-a", texto: "Seleciona todos os membros de uma classe de conjunto de 10 (T)" },
        { id: "14-b", texto: "Seleciona item de livro dado pergunta do tipo 'quando' (T)" },
        { id: "14-c", texto: "Seleciona item de livro dado pergunta do tipo 'como' (T)" },
        { id: "14-d", texto: "Seleciona item dado preposição após verbo (ex. comer com) (T)" },
        { id: "14-e", texto: "Seleciona item diferente em um conjunto de 5 para 25 itens (T)" },
        { id: "14-f", texto: "Seleciona item de conjunto de 10 quando solicitado 'O que falta?' (T)" },
        { id: "15-a", texto: "Seleciona item relacionado a eventos passados para 5 eventos (T)" },
        { id: "15-b", texto: "Seleciona item relacionado a eventos futuros para 5 eventos (T)" },
        { id: "15-c", texto: "Seleciona item solicitado 'quais desses não pode...?' (T)" },
        { id: "15-d", texto: "Seleciona item solicitado 'qual desses não é...?' (T)" },
        { id: "15-e", texto: "Seleciona itens baseados em 4 componentes verbais (T)" }
    ],

    INTRAVERBAL: [
        { id: "11-a", texto: "Completa 10 componentes duplos (subst-verbo) (T)" },
        { id: "11-b", texto: "Responde 25 componentes duplos em questão tipo 'onde' (T)" },
        { id: "11-c", texto: "Responde 25 componentes duplos em questão tipo 'quem' (T)" },
        { id: "11-d", texto: "Responde 25 questões tipo 'o que' envolvendo função (T)" },
        { id: "11-e", texto: "Responde 25 questões tipo 'o que' fornecendo a função (T)" },
        { id: "11-f", texto: "Demonstra 10 intraverbais não treinados (O)" },
        { id: "11-g", texto: "Demonstra 5 novos intraverbais somente com treino de tato (T/O)" },
        { id: "11-h", texto: "Responde 'eu não sei' para perguntas que não saiba (T/O)" },
        { id: "12-a", texto: "Fornece ao menos 3 membros de uma classe para 10 classes (T)" },
        { id: "12-b", texto: "Responde 25 questões de múltipla escolha (T)" },
        { id: "12-c", texto: "Fornece 10 categorias quando dado vários membros (T)" },
        { id: "12-d", texto: "Fornece o nome de 25 itens dado característica específica (T)" },
        { id: "12-e", texto: "Fornece 2 características de 10 itens dado seus nomes (T)" },
        { id: "12-f", texto: "Fornece uma resposta para 3 questões emocionais (T)" },
        { id: "12-g", texto: "Fornece 25 respostas com mais de 3 palavras por questão (T)" },
        { id: "13-a", texto: "Responde 25 questões com sim ou não (T)" },
        { id: "13-b", texto: "Descreve 5 locais que não estão visíveis (T)" },
        { id: "13-c", texto: "Responde 25 questões intraverbais envolvendo adjetivo (T)" },
        { id: "13-d", texto: "Responde uma questão sobre uma única frase lida (T)" },
        { id: "13-e", texto: "Responde corretamente a questão 'Qual a sua idade?' (T)" },
        { id: "13-f", texto: "Responde duas questões relativas a tempo com resposta genérica (T)" },
        { id: "13-g", texto: "Completa uma sequência de história para 5 histórias (T)" },
        { id: "13-h", texto: "Conversas com pelo menos 3 mudanças intraverbais em tópico único (T)" },
        { id: "13-i", texto: "Descreve 2 características sobre si mesmo (T)" },
        { id: "14-a", texto: "Responde 25 questões diferentes (quem/o que/onde) com 3+ elementos (T)" },
        { id: "14-b", texto: "Fornece 3 membros para 25 categorias (T)" },
        { id: "14-c", texto: "Responde 5 questões sobre eventos diários ou atuais (T)" },
        { id: "14-d", texto: "Responde intraverbalmente pelo menos 25 vezes ao dia a pares (O)" },
        { id: "14-e", texto: "Generalização fornecendo mesma resposta para questões variadas (T)" },
        { id: "14-f", texto: "Falará 3 coisas sobre um item para 25 itens (T)" },
        { id: "14-g", texto: "Fornece 3 partes de informações pessoais (T)" },
        { id: "14-h", texto: "Responde 25 questões intraverbais envolvendo preposições (T)" },
        { id: "14-i", texto: "Responde 25 questões intraverbais envolvendo pronomes (T)" },
        { id: "14-j", texto: "Fornece 25 respostas para questões sequenciais (T)" },
        { id: "14-k", texto: "Responde 10 questões com 'quando' (T)" },
        { id: "15-a", texto: "Responde 10 questões sobre serviços de ajuda à comunidade (T)" },
        { id: "15-b", texto: "Responde 25 questões contendo 4 ou mais partes da fala (T)" },
        { id: "15-c", texto: "Troca de turnos complementando história iniciada por outro (T/O)" },
        { id: "15-d", texto: "Responde 5 questões com 'como' (T)" },
        { id: "15-e", texto: "Fornece o último nome quando solicitado (T)" },
        { id: "15-f", texto: "Responde 25 questões intraverbais envolvendo advérbios (T)" },
        { id: "15-g", texto: "Resposta generalizada descrevendo objeto de três formas (T)" },
        { id: "15-h", texto: "Descreve 5 eventos que ocorreram no passado (T)" },
        { id: "15-i", texto: "Descreve 5 eventos que ocorrerão no futuro (T)" },
        { id: "15-k", texto: "Sugere uma possível solução quando apresentado um problema (T)" }
    ],

    ROTINA_GRUPO: [
        { id: "11-a", texto: "Senta ou permanece em atividade de arte por 5 minutos (O)" },
        { id: "11-b", texto: "Responde 1 instrução em grupo sem dica adicional (O)" },
        { id: "11-c", texto: "Trabalha independente em tarefa por um minuto (O)" },
        { id: "11-d", texto: "Vai para frente do grupo com 1 dica verbal (O)" },
        { id: "12-a", texto: "Levanta a mão para se manifestar em contexto de grupo (O)" },
        { id: "12-b", texto: "Usa apropriadamente materiais de sala de aula (O)" },
        { id: "12-c", texto: "Separa brinquedos e materiais quando solicitado (O)" },
        { id: "12-d", texto: "Mantém engajamento por 1 min em artes sem adulto na mesa (O)" },
        { id: "13-a", texto: "Recebe materiais necessários após orientação verbal (O)" },
        { id: "13-b", texto: "Transita independentemente entre atividades com instrução (O)" },
        { id: "13-c", texto: "Responde a um grupo de questões sem dica direta (O)" },
        { id: "13-d", texto: "Pede para usar o toalete e apresenta poucos acidentes (O)" },
        { id: "14-a", texto: "Reveza e compartilha coisas com os pares (O)" },
        { id: "14-b", texto: "Discrimina e segue grupo de instruções com dois componentes (O)" },
        { id: "14-c", texto: "Segue regras de segurança em sala de aula (O)" },
        { id: "14-d", texto: "Lidera 2 diferentes grupos de atividades com outras crianças (O)" },
        { id: "14-e", texto: "Pede por uma atividade específica em contexto de grupo" },
        { id: "14-f", texto: "Ajuda a recolher após atividade com apenas uma dica (O)" },
        { id: "15-a", texto: "Concentra-se em tarefa apesar de barulhos na sala (O)" },
        { id: "15-b", texto: "Encontra itens de autocuidado sem dicas (O)" },
        { id: "15-c", texto: "Interage verbalmente com pares 3 vezes em atividade de mesa (O)" },
        { id: "15-d", texto: "Volta a se sentar quando acaba a sua vez sem dicas (O)" },
        { id: "15-e", texto: "Mantém as mãos em si em ambiente de grupo (O)" },
        { id: "15-f", texto: "Levanta a mão para indicar resposta em grupo (O)" },
        { id: "15-g", texto: "Completa 2 folhas de exercício independentemente (O)" },
        { id: "15-h", texto: "Senta em reunião escolar por 20 minutos sem interrupção (O)" }
    ],

    ESTRUTURA_LINGUISTICA: [
        { id: "11-a", texto: "Emite verbos auxiliares em frase de mando ou tato (O)" },
        { id: "11-b", texto: "Frases contêm pequenas palavras apropriadas ao contexto (O)" },
        { id: "11-c", texto: "Usa marcadores de plural 's' vs 'is' (O)" },
        { id: "11-d", texto: "Usa corretamente plurais irregulares (O)" },
        { id: "12-a", texto: "Usa está e estou apropriadamente com verbos (T/O)" },
        { id: "12-b", texto: "Emite conjunções para combinar palavras e frases (O)" },
        { id: "12-c", texto: "Emite alguns verbos irregulares no passado adequadamente (T/O)" },
        { id: "12-d", texto: "Emite flexões no particípio presente 'verbo-ndo' (O)" },
        { id: "13-a", texto: "Fala de 3 a 5 palavras em frases (O)" },
        { id: "13-b", texto: "Emite locuções prepositivas (ex. abaixo de, acima de) (T/O)" },
        { id: "13-c", texto: "Emite adjetivos para modificar substantivos (O)" },
        { id: "13-d", texto: "Emite contrações em contexto verbal (O)" },
        { id: "13-e", texto: "Emite pronomes para modificar substantivos (O)" },
        { id: "14-b", texto: "Verbos concordam com os sujeitos (O)" },
        { id: "14-c", texto: "Verbos concordam com os números de sujeitos (O)" },
        { id: "14-d", texto: "Emite flexões adjetivas de grau comparativo/superlativo (T/O)" },
        { id: "14-e", texto: "Emite advérbios para modificar verbos (T/O)" },
        { id: "15-a", texto: "Emite frases conectadas por conjunções (O)" },
        { id: "15-b", texto: "Demonstra MLU de 5 morfemas (O)" },
        { id: "15-c", texto: "Pronomes concordam com o gênero (O)" },
        { id: "15-d", texto: "Pronomes concordam com número (O)" },
        { id: "15-e", texto: "Usa quantificação em uma sentença (sempre, nunca) (O)" },
        { id: "15-f", texto: "Usa demonstrativo em uma sentença (este, aquele) (O)" },
        { id: "15-g", texto: "Emite palavras que descrevem certeza (eu acho, talvez) (O)" }
    ],

    LEITURA: [
        { id: "11-a", texto: "Vira as páginas e olha para o livro por 30 segundos" },
        { id: "11-b", texto: "Pede para lerem histórias dos livros (O)" },
        { id: "11-c", texto: "Toca figuras nos livros que correspondem às histórias (T/O)" },
        { id: "12-a", texto: "Completa um quebra cabeça de ABC sem dicas (T/O)" },
        { id: "12-b", texto: "Recita 5 letras do alfabeto como dica inicial (T)" },
        { id: "12-c", texto: "Tem um livro favorito e dá nome ao ver capa (O)" },
        { id: "12-d", texto: "Tateia figuras enquanto adulto lê história (T/O)" },
        { id: "12-e", texto: "Pareia todas as letras maiúsculas (T)" },
        { id: "13-a", texto: "Recita ou canta o alfabeto inteiro (T)" },
        { id: "13-b", texto: "Pede para dizer quais palavras estão escritas (O)" },
        { id: "13-c", texto: "Finge ler um livro (O)" },
        { id: "13-d", texto: "Discrimina como ouvinte seu próprio nome em conjunto (T)" },
        { id: "13-e", texto: "Olha para palavras escritas mais que figuras (O)" },
        { id: "14-a", texto: "Discrimina a maioria das letras maiúsculas (T)" },
        { id: "14-b", texto: "Pareia 5 palavras em cartões às palavras no papel (T)" },
        { id: "14-c", texto: "Oferece nome da letra dado som e vice-versa (T)" },
        { id: "14-d", texto: "Relembra intraverbalmente 3 histórias lidas (T/O)" },
        { id: "14-e", texto: "Discriminação de ouvinte e tato de variações de letras (T)" },
        { id: "15-a", texto: "Indica se 2 palavras rimam em 10 rimas (T)" },
        { id: "15-b", texto: "Tateia a maioria das letras maiúsculas (T)" },
        { id: "15-c", texto: "Pareia 10 letras minúsculas com maiúsculas (T)" },
        { id: "15-d", texto: "Discrimina entre números e letras como ouvinte (T)" },
        { id: "15-e", texto: "Soletra seu próprio nome sem dicas (T)" },
        { id: "15-f", texto: "Seleciona 5 palavras escritas corretas de conjunto (T)" }
    ],

    ESCRITA: [
        { id: "11-a", texto: "Usa instrumento de escrita para marcar papel sob comando (T)" },
        { id: "11-b", texto: "Rabisca de forma independente no papel ou quadro (O)" },
        { id: "11-c", texto: "Demonstra dominância da mão direita ou esquerda (T/O)" },
        { id: "11-d", texto: "Imita movimentos horizontais de vai e vem (T)" },
        { id: "11-e", texto: "Imita movimentos verticais para cima e para baixo (T)" },
        { id: "11-f", texto: "Imita movimentos circulares pequenos e amplos (T)" },
        { id: "11-g", texto: "Imita movimentos diagonais e curvados (T)" },
        { id: "12-a", texto: "Demonstra pinça apropriada com instrumento (T/O)" },
        { id: "12-b", texto: "Imita o desenho de um quadrado e triângulo (T)" },
        { id: "12-c", texto: "Traça 3 formas e permanece dentro do espaço (T)" },
        { id: "12-d", texto: "Copia 3 formas diferentes dado o modelo (T)" },
        { id: "12-e", texto: "Desenha linha entre pontos A e B em trajetória curva (T)" },
        { id: "12-f", texto: "Copia 5 linhas e formas diferentes em conjunto (T)" },
        { id: "13-a", texto: "Copia 4 números ou letras (T)" },
        { id: "13-b", texto: "Combina formas independente para fazer figura (T)" },
        { id: "13-c", texto: "Desenha pessoa com 4 partes reconhecíveis (T)" },
        { id: "13-d", texto: "Traça seu próprio nome no papel dentro de 0,5cm (T)" },
        { id: "14-a", texto: "Copia de forma legível seu nome em papel com linhas (T)" },
        { id: "14-b", texto: "Colore imagens permanecendo dentro das linhas (T)" },
        { id: "14-c", texto: "Copia números de 1-10 de forma legível (T)" },
        { id: "14-d", texto: "Copia 10 letras maiúsculas e minúsculas legíveis (T)" },
        { id: "15-a", texto: "Desenha figuras reconhecíveis de 3 itens (T)" },
        { id: "15-b", texto: "Escreve legível 10 letras ou números quando ditados (T)" },
        { id: "15-c", texto: "Copia de forma legível 5 palavras simples (T)" }
    ],

    MATEMATICA: [
        { id: "11-a", texto: "Conta mecanicamente até 5 com ponto de partida verbal (T)" },
        { id: "11-b", texto: "Organiza objetos por tamanho (pequeno, médio, grande) (T)" },
        { id: "11-c", texto: "Distingue entre 1 e 2 itens como ouvinte (T)" },
        { id: "11-d", texto: "Distingue entre 1 e 2 itens como mando (T/O)" },
        { id: "11-e", texto: "Combina com o modelo números de 1-10 (T)" },
        { id: "12-a", texto: "Distingue entre 1 e 2 itens como tato (T)" },
        { id: "12-b", texto: "Conta de 1-5 com os dedos de forma correspondente (T)" },
        { id: "12-c", texto: "Distingue entre 1, 2 e 3 itens como ouvinte (T)" },
        { id: "12-d", texto: "Conta dois itens com correspondência 1:1 (T)" },
        { id: "13-a", texto: "Diz a idade quando perguntado (T)" },
        { id: "13-b", texto: "Conta até 3 itens a partir da instrução 'Quantos?' (T)" },
        { id: "13-c", texto: "Identifica como ouvinte o número de itens (matriz) (T)" },
        { id: "13-d", texto: "Demonstra enumeração na contagem (ênfase final no número) (T)" },
        { id: "14-a", texto: "Tateia corretamente coleção de 1-3 itens (T)" },
        { id: "14-b", texto: "Identifica coleção com mais ou menos que grupo comparação (T)" },
        { id: "14-c", texto: "Identifica recipiente como cheio ou vazio (T)" },
        { id: "14-d", texto: "Identifica item como maior ou menor que comparação (T)" },
        { id: "14-e", texto: "Identifica item como mais pesado ou leve que comparação (T)" },
        { id: "15-a", texto: "Desempenha ação número de vezes especificado (T)" },
        { id: "15-b", texto: "Completa sequência ou padrão contendo 2 elementos (T)" },
        { id: "15-c", texto: "Identifica termos ordinais 'primeiro' e 'último' (T)" },
        { id: "15-d", texto: "Identifica corretamente os tatos 'manhã' e 'noite' (T)" },
        { id: "15-e", texto: "Responde ao intraverbal qual número é o próximo (T)" },
        { id: "15-f", texto: "Identifica 3 moedas e diz o que fazer com dinheiro (T)" }
    ]
};