// taskAnalysisLevel2.js
// VB-MAPP – Task Analysis – NÍVEL 2 (INTEGRAL - 100% ALINHADO À PLANILHA)

export const LEVEL_2_TASKS = {
    MANDO: [
        { id: "6-a", texto: "Espontaneamente emite 5 mandos sem o objeto presente e sem dica verbal (O)" },
        { id: "6-b", texto: "Emite 10 mandos diferentes sem dica ecoica ou imitativa – o objeto pode estar presente (T/O)" },
        { id: "6-c", texto: "Mandos por 5 diferentes itens que não estão presentes, sem dica (T/O)" },
        { id: "6-d", texto: "Generaliza 4 mandos com diferentes pessoas (T/O)" },
        { id: "6-e", texto: "Mantém um mando recém adquirido por um item que não está presente após 24 horas (T/O)" },
        { id: "7-a", texto: "Pede duas vezes com 2 palavras em uma frase ou sentença (ex. Beber suco) (TO: 60 min.)" },
        { id: "7-b", texto: "Pede para os outros indivíduos emitirem 2 ações diferentes com dica verbal (ex. ir, girar) (T/O)" },
        { id: "7-c", texto: "Emite dois mandos para remover itens ou atividades indesejáveis (O)" },
        { id: "7-d", texto: "Generaliza resposta para 2 diferentes mandos (ex. copo/bebida; cachorro/Maggie) (O)" },
        { id: "7-e", texto: "Variação apropriada de entonação para OMs positivas ou negativas por 5 vezes (O)" },
        { id: "7-f", texto: "Pede por ajuda ou assistência 2 vezes (O)" },
        { id: "7-g", texto: "Alta frequência de mandos (15 em um período de 5 minutos) (O)" },
        { id: "8-a", texto: "Pede 5 vezes com 2 palavras em uma frase ou sentença (TO: 120 min.)" },
        { id: "8-b", texto: "Mandos por informações usando questões com 'o que' 2 vezes (ex. O que é isso?) (T/O)" },
        { id: "8-c", texto: "Mandos com um pronome 2 vezes (ex. Meu trem. Esse é o seu) (O)" },
        { id: "8-d", texto: "Mandos ocorrem com 3 frases possessivas diferentes (ex. Eu quero... Isso é meu...) (O)" },
        { id: "8-e", texto: "Mandos com sim e não por 4 vezes (ex. Você quer passeio? Sim.) (T/O)" },
        { id: "8-f", texto: "Mandos por informações 2 vezes usando questões com Onde (ex. Onde está Elmo?) (T/O)" },
        { id: "9-a", texto: "Espontaneamente emite 50 mandos por dia (sem dicas verbais) (O)" },
        { id: "9-b", texto: "Adquire 2 mandos após treinamento de tato ou ecoico (O)" },
        { id: "9-c", texto: "Mandos por informação usando pronomes interrogativos por 25 vezes (O)" },
        { id: "9-d", texto: "Mandos com um adjetivo por 5 vezes (ex. batata frita grande, carro vermelho) (O)" },
        { id: "9-e", texto: "Emite 5 mandos em 30 segundos (ex. durante um jogo na água) (TO: 30s)" },
        { id: "9-f", texto: "Mandos contendo frases com 3 palavras por 10 vezes (ex. Esse é meu cavalo.) (O)" },
        { id: "10-a", texto: "Emite 2 novos mandos sem treino (ex. Eu quero chocolate quente) (O)" },
        { id: "10-b", texto: "Generalização de respostas com 2 mandos diferentes (ex. Me pegue. Corre.) (O)" },
        { id: "10-c", texto: "Mandos com um adjetivo por 5 vezes – pode usar dicas verbais e não verbais (O)" },
        { id: "10-d", texto: "Mandos por informação 3 vezes, usando perguntas com Quem (O)" },
        { id: "10-e", texto: "Mandos espontâneos para outros, emitindo 20 ações diferentes (O)" },
        { id: "10-f", texto: "Mandos espontâneos para um estranho ou alguém não familiar por 2 vezes (O)" }
    ],

    TATO: [
        { id: "6-a", texto: "Tateia 4 diferentes pessoas, animais ou personagens pelo nome (T)" },
        { id: "6-b", texto: "Tateia 2 ações (ex: pulando, batendo palmas) (T)" },
        { id: "6-c", texto: "Adquire um novo tato em menos de 20 tentativas de treino (T)" },
        { id: "6-d", texto: "Tateia 5 itens em um período de 15 segundos (fluência) (T)" },
        { id: "7-a", texto: "Tateia 3 partes do corpo (ex: nariz, olhos, boca) (T)" },
        { id: "7-b", texto: "Tateia 2 estímulos auditivos (ex: telefone, sirene, latido) (T)" },
        { id: "7-c", texto: "Espontaneamente tateia usando duas palavras em 5 tatos (ex: bebê chorando) (T/O)" },
        { id: "7-d", texto: "Tateia 2 ações diferentes (ex: bebendo, nadando) (T)" },
        { id: "7-e", texto: "Tateia 40 itens quando perguntado 'O que é isso?' (T)" },
        { id: "8-a", texto: "Tateia 3 estímulos tateáveis (ex. diz bola ao sentir dentro de sacola) (T)" },
        { id: "8-b", texto: "Tateia 5 combinações substantivo-verbo ou verbo-substantivo (T)" },
        { id: "8-c", texto: "Tateia 2 ou mais itens de 10 páginas diferentes de um livro (T)" },
        { id: "8-d", texto: "Olha de relance para um ouvinte enquanto tateia em 5 ocasiões (O)" },
        { id: "9-a", texto: "Tateia 25 relações substantivo-substantivo (ex: papel e lápis) (T)" },
        { id: "9-b", texto: "Adquire um novo tato em menos de 15 tentativas de treino (T)" },
        { id: "9-c", texto: "Tateia espontaneamente em livros, TV ou vídeo por 5 vezes (O)" },
        { id: "9-d", texto: "Aprende 2 novos tatos sem treino direto (transferência ecoico-tato) (T)" },
        { id: "9-e", texto: "Generalização de resposta por 5 itens (ex: Katie/Professora; Garfield/Gato) (T/O)" },
        { id: "10-a", texto: "Tateia 10 ações (escalando, jogando, pintando, nadando, lavando) (T/O)" },
        { id: "10-b", texto: "Tateia 2 estímulos gustativos (ex. tateia laranja ao provar) (T/O)" },
        { id: "10-c", texto: "Tateia 20 itens em 1 minuto em teste de fluência (T)" },
        { id: "10-d", texto: "Tateia 2 cores diferentes (vermelho, azul) (T/O)" },
        { id: "10-e", texto: "Tateia 2 formas diferentes (ex: círculo, estrela) (T/O)" }
    ],

    OUVINTE: [
        { id: "6-a", texto: "Seleciona item em conjunto de 5, por 25 diferentes itens (T)" },
        { id: "6-b", texto: "Adquire nova habilidade de ouvinte em menos de 25 tentativas (T)" },
        { id: "6-c", texto: "Discrimina 6 pessoas, animais, ou personagens pelo nome (T)" },
        { id: "6-d", texto: "Generaliza ouvinte entre 3 exemplos de 25 itens diferentes (T)" },
        { id: "7-a", texto: "Vai até 3 pessoas específicas sob comando (ex: Vá até Debbie) (T)" },
        { id: "7-b", texto: "Aponta para um item nomeado em um livro em 5 itens (T)" },
        { id: "7-c", texto: "Seleciona 5 itens do ambiente natural sob comando (T/O)" },
        { id: "7-d", texto: "Demonstra espontaneamente 5 habilidades de ouvinte no ambiente natural (O)" },
        { id: "8-a", texto: "Vai até 3 locais diferentes sob comando (ex: Vá até a cozinha) (T)" },
        { id: "8-b", texto: "Seleciona item de conjunto de 8, com 2 estímulos similares, por 20 itens (T)" },
        { id: "8-c", texto: "Seleciona item ao ouvir o som referente (ex. Latido para cachorro) (T)" },
        { id: "8-d", texto: "Seleciona 2 itens de conjunto de 8 por 5 pares (substantivo-substantivo) (T)" },
        { id: "9-a", texto: "Adquire 2 novas respostas de ouvinte sem treino formal (O)" },
        { id: "9-b", texto: "Responde apropriadamente a 5 gestos (ex. silêncio, pare) (T/O)" },
        { id: "9-c", texto: "Demonstra 3 ações específicas para 3 pessoas diferentes (T)" },
        { id: "9-d", texto: "Seleciona 2 itens alvo de uma cena/livro em 10 conjuntos (nome-nome) (T)" },
        { id: "10-a", texto: "Realiza 2 ações consecutivas para 10 conjuntos (verbo-verbo) (T)" },
        { id: "10-b", texto: "Discrimina entre 2 cores em um conjunto de 4 objetos (T)" },
        { id: "10-c", texto: "Discrimina entre 2 formas em um conjunto de 4 formas (T)" },
        { id: "10-d", texto: "Generaliza ouvinte substantivo-verbo com novos objetos para 5 ações (T)" },
        { id: "10-e", texto: "Generaliza ouvinte substantivo-verbo com nova ação para 5 objetos (T)" }
    ],

    PERCEPCAO_VISUAL: [
        { id: "6-a", texto: "Conecta 2 itens ou objetos juntos (ex: Duplos, Legos) (O)" },
        { id: "6-b", texto: "Encaixa objetos idênticos em uma pilha 2 vezes (O)" },
        { id: "6-c", texto: "Vira 2 páginas em um livro (T/O)" },
        { id: "6-d", texto: "Completa 3 quebra-cabeças diferentes contendo 3-4 peças (T/O)" },
        { id: "6-e", texto: "Empilha 4 blocos sem ajuda (O)" },
        { id: "6-f", texto: "Pareia objetos/figuras idênticos em conjunto de 3, para 10 itens (T)" },
        { id: "6-g", texto: "Pareia objetos/figuras idênticos de tamanhos diferentes em conjunto de 6 (T)" },
        { id: "6-h", texto: "Coloca 5 itens no lugar correto de acordo com o contexto (T/O)" },
        { id: "7-a", texto: "Completa 5 quebra-cabeças diferentes de 6 ou mais peças (T/O)" },
        { id: "7-b", texto: "Pareia objetos/figuras idênticos em conjunto de 8, para 25 objetos (T)" },
        { id: "7-c", texto: "Pareia figuras idênticas com fundos diferentes em conjunto de 8 (T)" },
        { id: "7-d", texto: "Pareia figuras (2D) com objetos (3D) em conjunto de 8, para 10 pares (T)" },
        { id: "7-e", texto: "Pareia espontaneamente 2 itens juntos em brincadeira (O)" },
        { id: "7-f", texto: "Completa pareamento idêntico em conjunto de 8 em menos de 20s (T)" },
        { id: "8-a", texto: "Generaliza para 5 novas habilidades de pareamento sem treino formal (T/O)" },
        { id: "8-b", texto: "Pareia itens idênticos com o correspondente em livro para 25 itens (T)" },
        { id: "8-c", texto: "Pareia itens idênticos no ambiente natural para 25 itens (T)" },
        { id: "8-d", texto: "Seleciona 3 objetos não idênticos, mas associados, de uma caixa (T)" },
        { id: "8-e", texto: "Monta sucessivamente 5 partes de 5 brinquedos de montar (T)" },
        { id: "9-a", texto: "Pareia itens idênticos porém de cores diferentes em conjunto de 8 (T)" },
        { id: "9-b", texto: "Pareia objetos não idênticos em conjunto de 8 com estímulos similares (T)" },
        { id: "9-c", texto: "Pareia itens não idênticos ao correspondente em livro para 25 itens (T)" },
        { id: "9-d", texto: "Pareia itens não idênticos no ambiente natural para 25 itens (T)" },
        { id: "9-e", texto: "Demonstra pareamento espontâneo funcional (ex. par do sapato) (T)" },
        { id: "10-a", texto: "Monta, junta ou agrupa 5 brinquedos diferentes que vão juntos (T)" },
        { id: "10-b", texto: "Pareia figuras de partes do corpo com o seu próprio corpo para 5 partes (T/O)" },
        { id: "10-c", texto: "Pareia a figura de uma ação com uma figura não idêntica da mesma ação (T)" },
        { id: "10-d", texto: "Pinta figuras em um livro de colorir (T)" },
        { id: "10-e", texto: "Pareia 10 itens diferentes que são associados entre si (ex. Sapato e meia) (T)" }
    ],

    BRINCAR: [
        { id: "6-a", texto: "Transporta 2 ou mais brinquedos enquanto anda (O)" },
        { id: "6-b", texto: "Brinca independente com um quebra cabeças por 1 minuto (O)" },
        { id: "6-c", texto: "Engaja-se em uma brincadeira sensorial por 2 minutos (ex. areia) (O)" },
        { id: "6-d", texto: "Espirra água e brinca com objetos em uma piscina (O)" },
        { id: "6-e", texto: "Brinca em ambiente com brinquedos com várias partes por 2 min (O)" },
        { id: "7-a", texto: "Rabisca em Magna Doodle, quadro branco ou papel (O)" },
        { id: "7-b", texto: "Espera enquanto a atividade está sendo organizada (O)" },
        { id: "7-c", texto: "Brinca independente por 2 minutos sem a interação de um adulto (O)" },
        { id: "7-d", texto: "Sorteia ou separa um item do brinquedo preferido de outros (O)" },
        { id: "7-e", texto: "Imita espontaneamente um adulto usando um objeto (ex. escovar cabelo) (O)" },
        { id: "8-a", texto: "Brinca independente em playground por 2 min sem dica (O)" },
        { id: "8-b", texto: "Observa e imita outra criança em brincadeira estruturada (O)" },
        { id: "8-c", texto: "Atividades motoras finas por 1 minuto (contas, laços) (O)" },
        { id: "8-d", texto: "Brinca com 2 brinquedos no contexto correto (O)" },
        { id: "9-a", texto: "Manda para ir ao playground ou pede ajuda para alcançar brinquedo (O)" },
        { id: "9-b", texto: "Completa 5 quebra cabeças com 5 ou mais peças (O)" },
        { id: "9-c", texto: "Brinca repetidamente em componentes de estrutura de brincar (O)" },
        { id: "9-d", texto: "Chuta a bola para frente espontaneamente (O)" },
        { id: "10-a", texto: "Brinca com um brinquedo funcionalmente (ex: jogo de aniversário) (O)" },
        { id: "10-b", texto: "Permite que outros brinquem próximos (O)" },
        { id: "10-c", texto: "Demonstra interesse em projeto realizado por colega (O)" },
        { id: "10-d", texto: "Pede para outra criança não atrapalhar a sua estrutura (O)" },
        { id: "10-e", texto: "Improvisa quando estão faltando partes (O)" },
        { id: "10-f", texto: "Ajuda a pegar os brinquedos com dica de um adulto (O)" }
    ],

    SOCIAL: [
        { id: "6-a", texto: "Olha para o colega quando este fala 2 vezes (O)" },
        { id: "6-b", texto: "Persegue/segue o colega na brincadeira com dica de um adulto (O)" },
        { id: "6-c", texto: "Senta com colegas em atividade de grupo sem interrupção por 2 min (O)" },
        { id: "6-d", texto: "Engaja-se com brincadeiras físicas com colegas com dica 2 vezes (O)" },
        { id: "6-e", texto: "Espontaneamente imita 5 diferentes comportamentos dos colegas (O)" },
        { id: "7-a", texto: "Pede ao colega com dica de um adulto 5 vezes (T)" },
        { id: "7-b", texto: "Ecoa sons e palavras dos colegas com dica 2 vezes (T)" },
        { id: "7-c", texto: "Espontaneamente atenta para outra criança em atividade lúdica (O)" },
        { id: "7-d", texto: "Espontaneamente oferece um reforçador ao colega 1 vez (O)" },
        { id: "8-a", texto: "Espontaneamente cumprimenta outros com aceno ou vocal (O)" },
        { id: "8-b", texto: "Espontaneamente imita ações de colega com objetos 2 vezes (O)" },
        { id: "8-c", texto: "Responde aos pedidos dos colegas com dica 2 vezes (T/O)" },
        { id: "8-d", texto: "Espontaneamente ecoa palavras do colega 2 vezes (O)" },
        { id: "9-a", texto: "Espontaneamente copia do colega a montagem de um item 1 vez (O)" },
        { id: "9-b", texto: "Responde apropriadamente a pedidos de objeto 2 vezes (O/T)" },
        { id: "9-c", texto: "Responde apropriadamente a pedidos de ação 2 vezes (O/T)" },
        { id: "9-d", texto: "Responde a pedidos de colegas para cessar comportamento (O/T)" },
        { id: "9-e", texto: "Espontaneamente pede ajuda de adultos 1 vez (O)" },
        { id: "9-f", texto: "Tateia itens para benefício de colegas com dica 2 vezes (O)" },
        { id: "10-a", texto: "Espontaneamente pede aos colegas para seguir direções (O)" },
        { id: "10-b", texto: "Espontaneamente pede aos outros para atentar para o que olha (O)" },
        { id: "10-c", texto: "Espontaneamente pede aos outros para atentar para seu comportamento (O)" },
        { id: "10-d", texto: "Pede atenção de colegas 2 vezes (ex: 'Oi Johnny!') (O)" },
        { id: "10-e", texto: "Espontaneamente imita um colega montando algo 2 vezes (O)" }
    ],

    IMITACAO: [
        { id: "6-a", texto: "Imita assopro 2 vezes (ex: bolhas, velas, balões) (T)" },
        { id: "6-b", texto: "Imita 5 gestos comuns (ex. positivo, dedo na boca) (O/T)" },
        { id: "6-c", texto: "Imita virar a página de um livro (T)" },
        { id: "6-d", texto: "Imita 5 ações com objeto específico selecionado de conjunto de 2 (T)" },
        { id: "6-e", texto: "Imita puxando 5 diferentes itens separados (ex. Duplos) (T)" },
        { id: "7-a", texto: "Imita 3 comportamentos de brincadeira natural (ex. rampa) (T)" },
        { id: "7-b", texto: "Imita 5 comportamentos de duas sequências (O/T)" },
        { id: "7-c", texto: "Espontaneamente imita comportamento observado na TV ou vídeo (O)" },
        { id: "7-d", texto: "Imita 5 expressões faciais (ex. amassando nariz) (T)" },
        { id: "7-e", texto: "Mantém comportamento imitativo recém adquirido após 24h (T)" },
        { id: "7-f", texto: "Imita um novo comportamento na primeira tentativa (O/T)" },
        { id: "7-g", texto: "Imita 5 exemplos de jogo de dedo (T)" },
        { id: "8-a", texto: "Imita 5 ações em 10 segundos com fluência (T)" },
        { id: "8-b", texto: "Imita desenhando um círculo em 2 ocasiões (T)" },
        { id: "8-c", texto: "Imita fingindo 5 atividades lúdicas (ex: um monstro) (T)" },
        { id: "8-d", texto: "Espontaneamente imita 5 movimentos motores finos de arte (O)" },
        { id: "8-e", texto: "Adquire 5 novas habilidades de ouvinte via transferência de imitação (T)" },
        { id: "8-f", texto: "Imita outra criança durante atividades diárias 2 vezes (O)" },
        { id: "8-g", texto: "Repete comportamento divertido observado anteriormente (atrasada) (T)" },
        { id: "9-a", texto: "Imita atividade sócio-dramática modelada por colegas (T)" },
        { id: "9-b", texto: "Espontaneamente imita 5 comportamentos em atividade de grupo (O)" },
        { id: "9-c", texto: "Imita 10 ações de dois componentes (O/T)" },
        { id: "9-d", texto: "Imita comportamento rápido e devagar para 5 comportamentos (T)" },
        { id: "10-a", texto: "Imita construção de itens ou construção de jogo de brinquedo (O/T)" },
        { id: "10-b", texto: "Imita 5 sequências de autocuidado (ex. escovar dentes) (O/T)" },
        { id: "10-c", texto: "Imita 5 atividades funcionais de vida diária (ex. varrer) (O/T)" },
        { id: "10-d", texto: "Imita comportamentos de adulto na brincadeira de simulação (O)" },
        { id: "10-e", texto: "Imita 50 diferentes comportamentos motores em comando (O/T)" }
    ],

    FCC: [
        { id: "6-a", texto: "Seleciona animal em conjunto de 3 para 5 sons (T)" },
        { id: "6-b", texto: "Seleciona objeto em conjunto de 3 para 5 sons (T)" },
        { id: "6-c", texto: "Seleciona item de conjunto de 3 para 5 músicas (T)" },
        { id: "7-a", texto: "Seleciona item de conjunto de 5 para 5 frases incompletas (T)" },
        { id: "7-b", texto: "Seleciona item de conjunto de 5 para associar palavras (T)" },
        { id: "7-c", texto: "Inverte 5 associações adquiridas em formato LRFFC (T)" },
        { id: "7-d", texto: "Generaliza 10 respostas FCC para tons de voz e volume (T)" },
        { id: "7-e", texto: "Generaliza 10 respostas FCC para novas frases sem treino (T)" },
        { id: "7-f", texto: "Generaliza 10 respostas FCC para 2 exemplares diferentes (T/O)" },
        { id: "8-a", texto: "Seleciona item de conjunto de 8 para 10 frases funcionais (T)" },
        { id: "8-b", texto: "Seleciona item de conjunto de 8 para 10 declarações de características (T)" },
        { id: "8-c", texto: "Seleciona item de conjunto de 8 para 10 declarações de classes (T)" },
        { id: "8-d", texto: "Seleciona item de conjunto de 8 para 10 questões 'Qual?' (T/O)" },
        { id: "8-e", texto: "Seleciona item de conjunto de 8 para 10 questões 'O que?' (T/O)" },
        { id: "8-f", texto: "Seleciona item de conjunto de 8 para 10 questões 'Quem?' (T/O)" },
        { id: "9-a", texto: "Generaliza classe de ROFCC com 5 exemplares para 10 classes (T)" },
        { id: "9-b", texto: "Emite 10 respostas ROFCC em no mínimo 1 minuto (fluência) (T)" },
        { id: "9-c", texto: "Seleciona item dado 2 declarações verbais independentes (T)" },
        { id: "9-d", texto: "Seleciona item em conjunto de 10 para 10 questões 'Onde?' (T)" },
        { id: "9-e", texto: "Demonstra 10 respostas de ROFCC em ambiente natural (T)" },
        { id: "10-a", texto: "Seleciona item em conjunto de 10 dada classe e função para 25 itens (T/O)" },
        { id: "10-b", texto: "Seleciona item em conjunto de 10 dada classe e característica (T/O)" },
        { id: "10-c", texto: "Demonstra 5 respostas FCC não treinadas em ambiente natural (T)" },
        { id: "10-d", texto: "Generaliza 25 novas tarefas LRFFC de dois componentes (T/O)" },
        { id: "10-e", texto: "Emite espontaneamente 5 respostas LRFFC contextuais (O)" }
    ],

    INTRAVERBAL: [
        { id: "6-a", texto: "Fornece o som feito por 2 animais ou objetos (T)" },
        { id: "6-b", texto: "Dá 2 nomes de animais dado o som que faz (T)" },
        { id: "6-c", texto: "Completa 5 sons diferentes em espaços (músicas) (T)" },
        { id: "6-d", texto: "Completa 2 espaços verbais de atividades divertidas (T)" },
        { id: "7-a", texto: "Completa 5 espaços em diferentes contextos (T)" },
        { id: "7-b", texto: "Responde corretamente a 5 espaços com contextos revertidos (T)" },
        { id: "7-c", texto: "Completa 5 espaços em branco em frases fora de contexto (T)" },
        { id: "7-d", texto: "Generaliza 10 respostas intraverbais para novo adulto/ambiente (T/O)" },
        { id: "8-a", texto: "Completa espaços de classificação de 2 comidas e 2 bebidas (T)" },
        { id: "8-b", texto: "Completa espaços em branco com 5 combinações subst-subst (T)" },
        { id: "8-c", texto: "Completa 5 músicas com duas ou mais palavras (T)" },
        { id: "8-d", texto: "Generaliza 10 respostas intraverbais para novas frases (E)" },
        { id: "9-a", texto: "Completa 10 espaços com combinações substantivo-verbo (T)" },
        { id: "9-b", texto: "Emite 2 respostas intraverbais espontaneamente (O)" },
        { id: "9-c", texto: "Responde 10 questões 'O que' com verbo como SD primário (T)" },
        { id: "9-d", texto: "Responde 10 questões 'O que' com substantivo como SD primário (T)" },
        { id: "9-e", texto: "Fornece dois ou mais membros quando perguntado O que come/bebe (T)" },
        { id: "9-f", texto: "Fornece 5 respostas novas para questões adquiridas (T)" },
        { id: "10-a", texto: "Responde 5 questões 'onde' diferentes (T)" },
        { id: "10-b", texto: "Responde 5 questões 'quem' diferentes (T)" },
        { id: "10-c", texto: "Demonstra 2 respostas intraverbais não treinadas (T)" },
        { id: "10-d", texto: "Responde 10 questões de classes diferentes (T)" },
        { id: "10-e", texto: "Responde cores e nomes de 10 itens visíveis (T)" },
        { id: "10-f", texto: "Responde 10 questões de funções diferentes (T)" },
        { id: "10-g", texto: "Emite espontaneamente 5 mandos intraverbais (T/O)" }
    ],

    ROTINA_GRUPO: [
        { id: "6-a", texto: "Ajusta-se ao se separar dos pais sem chorar (O)" },
        { id: "6-b", texto: "Senta por 1 minuto para lanchar ou almoçar com ajuda (O)" },
        { id: "6-c", texto: "Alinha-se com outra criança quando ajudado (O)" },
        { id: "6-d", texto: "Demonstra complacência para todos os alunos (O)" },
        { id: "7-a", texto: "Não tenta sair quando outra criança senta ao lado (O)" },
        { id: "7-b", texto: "Coloca um item pessoal longe com dica gestual ou verbal (O)" },
        { id: "7-c", texto: "Vai e senta à mesa com outra criança com dica verbal (O)" },
        { id: "7-d", texto: "Coopera para lavar as mãos com ajuda física (O)" },
        { id: "7-e", texto: "Não se engaja em inadequados ao lado de colega (O)" },
        { id: "8-a", texto: "Vai para a rodinha em grupo com dica verbal (O)" },
        { id: "8-b", texto: "Senta à mesa ou estação de trabalho com dica verbal (O)" },
        { id: "8-c", texto: "Espera sentado sem tocar materiais até permissão (O)" },
        { id: "8-d", texto: "Senta na rodinha por 2 min sem comportamento inadequado (O)" },
        { id: "9-a", texto: "Entra após recesso somente com dicas verbais (O)" },
        { id: "9-b", texto: "Participa de movimentos em grupo e músicas com dica verbal (O)" },
        { id: "9-c", texto: "Imita atividades com objeto em grupo (O)" },
        { id: "9-d", texto: "Canta músicas com o grupo com dica verbal (O)" },
        { id: "10-a", texto: "Leva bandeja/pratos para a pia com dica verbal (O)" },
        { id: "10-b", texto: "Consegue almoçar com dica verbal (O)" },
        { id: "10-c", texto: "Guarda mochila/casaco com dica para o grupo (T/O)" },
        { id: "10-d", texto: "Pega e guarda itens do lanche independentemente (O)" },
        { id: "10-e", texto: "Responde verbalmente em situação de grupo (O)" },
        { id: "10-f", texto: "Imita colegas cantando em situação de grupo (O)" },
        { id: "10-g", texto: "Vai ao banheiro sem comportamento inadequado com ajuda (O)" }
    ],

    ESTRUTURA_LINGUISTICA: [
        { id: "7-a", texto: "Usa palavras reconhecíveis mais frequentemente que jargões" },
        { id: "7-b", texto: "Emite frases com 2 a 3 palavras (O)" },
        { id: "7-c", texto: "Tem um vocabulário expressivo total de 50 palavras" },
        { id: "8-a", texto: "Emite mandos com 2 palavras para pedir 'mais' (O)" },
        { id: "8-b", texto: "Emite mandos/tatos com 2 palavras (subst-verbo) (O)" },
        { id: "8-c", texto: "Ajusta o volume de voz após comando (sussurro/alto) (T)" },
        { id: "8-d", texto: "Ecoa 10 ritmos, entonações ou passos diferentes (T)" },
        { id: "9-a", texto: "Consistentemente emite as consoantes iniciais das palavras" },
        { id: "9-b", texto: "Emite mandos com 2 palavras para posse (Meu biscoito) (O)" },
        { id: "9-c", texto: "Emite mandos ou tatos com 2 palavras para localização (O)" },
        { id: "9-d", texto: "Emite mandos com 2 palavras para negação ou recusa (O)" },
        { id: "9-e", texto: "Combina 2 palavras para fazer uma frase nova (O)" },
        { id: "10-a", texto: "Repertório ecóico generalizado (ecoa a maioria das palavras)" },
        { id: "10-b", texto: "Estranhos entendem pelo menos 50% das palavras (O)" },
        { id: "10-c", texto: "Emite um vocabulário receptivo total com 400 palavras" },
        { id: "10-d", texto: "Comprimento médio de sentenças de 2.5 morfemas (O)" }
    ]
};